application: mirror-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /glass/glass\.js
  static_files: static/glass/glass.js
  upload: static/glass/glass\.js

- url: /glass/glass\.css
  static_files: static/glass/glass.css
  upload: static/glass/glass\.css

- url: /js/service\.js
  static_files: static/service/service.js
  upload: static/service/service\.js

- url: /css/service\.css
  static_files: static/service/service.css
  upload: static/service/service\.css

- url: /_ah/spi/.*
  script: apis.ApiServer

- url: .*
  script: service.app

libraries:
- name: pycrypto
  version: latest
