application: mirror-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /glass/(.*\.(html|css|js|grxml))
  static_files: emulator/static/\1
  upload: emulator/static/(.*\.(html|css|js|grxml))

- url: /glass/images
  static_dir: emulator/static/images

- url: /_ah/spi/.*
  script: mirror_api.api.ApiServer

- url: /images
  static_dir: static/images

- url: /js/service\.js
  static_files: static/service/service.js
  upload: static/service/service\.js

- url: /css/service\.css
  static_files: static/service/service.css
  upload: static/service/service\.css

- url: /upload/.*
  script: mirror_api.upload.app

- url: .*
  script: main.app

libraries:
- name: pycrypto
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
