application: mirror-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /glass
  static_dir: static/glass

- url: /_ah/spi/.*
  script: apis.ApiServer

- url: .*
  script: service.app
  
libraries:
- name: pycrypto
  version: latest
